import { TTheme } from "./TTheme";

export type TPropertiesCSS = {
  width?: string | number | [] | any;
  height?: string | number | [] | any;
  color?: string | number | [];
  alignItems?: string | number | [];
  background?: string | number | [];
  backgroundColor?: string | number | [];
  borderBottomStyle?: string | number | [];
  borderBottomColor?: string | number | [];
  borderBottomWidth?: string | number | [];
  backgroundRepeat?: string | number | [] | any;
  backgroundPosition?: string | number | [] | any;
  backgroundSize?: string | number | [] | any;
  backgroundImage?: string | number | [] | any;
  cursor?: string | number | [];
  display?: string | number | [];
  flexDirection?: string | number | [];
  fontSize?: string | number | [];
  letterSpacing?: string | number | [];
  position?: string | number | [];
  justifyContent?: string | number | [];
  transition?: string | number | [];
  textAlign?: string | number | [];
  px?: string | number | [];
  py?: string | number | [];
  p?: string | number | [];
  padding?: string | number | [];
  pt?: string | number | [];
  pr?: string | number | [];
  pb?: string | number | [];
  pl?: string | number | [];
  mx?: string | number | [];
  my?: string | number | [];
  margin?: string | number | [];
  m?: string | number | [];
  mt?: string | number | [];
  mr?: string | number | [];
  mb?: string | number | [];
  ml?: string | number | [];
  active?: TPropertiesCSS | string | number | [] | any;
  hover?: TPropertiesCSS | string | number | [] | any;
};
